# yaml-language-server: $schema=./page-schema-1.json

# Page: config_spacecraft_configuration_types — list view.

title: spacecraft configuration types

body:
  - kind: crud
    table: config_spacecraft_configuration_types
    params: {}
