# yaml-language-server: $schema=./page-schema-1.json

# Page: config_agency_types — list view.

title: agency types

elements:
  - kind: tableview
    spot: body
    table: config_agency_types
    params: {}
