# yaml-language-server: $schema=./page-schema-1.json

# Page: config_astronaut_statuses — list view.

title: astronaut statuses

elements:
  - kind: tableview
    spot: body
    table: config_astronaut_statuses
    params: {}
