# yaml-language-server: $schema=./page-schema-1.json

# Page: config_image_licenses — list view.

title: image licenses

elements:
  - kind: tableview
    spot: body
    table: config_image_licenses
    params: {}
