# yaml-language-server: $schema=./table-schema-1.json

# Table: config_landing_types — lookup table for landing_types.

datasource: ll2
title: landing_types
table: "config/landing_types/"

columns:
  - { name: id, type: int, flags: [id] }
  - { name: name, type: string, flags: [title, searchable] }
  - { name: abbrev, type: string }
  - { name: description, type: string }
