# yaml-language-server: $schema=./table-schema-1.json

# Table: config_image_variant_types — lookup table for image_variant_types.

datasource: ll2
title: image_variant_types
table: "config/image_variant_types/"

columns:
  - { name: id, type: int, flags: [id] }
  - { name: name, type: string, flags: [title, searchable] }
