// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Account {
    pub identity: __sdk::Identity,
    pub handle: String,
    pub bankroll: i64,
    pub lifetime_won: i64,
    pub lifetime_lost: i64,
    pub games_played: u32,
    pub games_won: u32,
    pub registered_at: __sdk::Timestamp,
    pub banned: bool,
}

impl __sdk::InModule for Account {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Account`.
///
/// Provides typed access to columns for query building.
pub struct AccountCols {
    pub identity: __sdk::__query_builder::Col<Account, __sdk::Identity>,
    pub handle: __sdk::__query_builder::Col<Account, String>,
    pub bankroll: __sdk::__query_builder::Col<Account, i64>,
    pub lifetime_won: __sdk::__query_builder::Col<Account, i64>,
    pub lifetime_lost: __sdk::__query_builder::Col<Account, i64>,
    pub games_played: __sdk::__query_builder::Col<Account, u32>,
    pub games_won: __sdk::__query_builder::Col<Account, u32>,
    pub registered_at: __sdk::__query_builder::Col<Account, __sdk::Timestamp>,
    pub banned: __sdk::__query_builder::Col<Account, bool>,
}

impl __sdk::__query_builder::HasCols for Account {
    type Cols = AccountCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            handle: __sdk::__query_builder::Col::new(table_name, "handle"),
            bankroll: __sdk::__query_builder::Col::new(table_name, "bankroll"),
            lifetime_won: __sdk::__query_builder::Col::new(table_name, "lifetime_won"),
            lifetime_lost: __sdk::__query_builder::Col::new(table_name, "lifetime_lost"),
            games_played: __sdk::__query_builder::Col::new(table_name, "games_played"),
            games_won: __sdk::__query_builder::Col::new(table_name, "games_won"),
            registered_at: __sdk::__query_builder::Col::new(table_name, "registered_at"),
            banned: __sdk::__query_builder::Col::new(table_name, "banned"),
        }
    }
}

/// Indexed column accessor struct for the table `Account`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountIxCols {
    pub bankroll: __sdk::__query_builder::IxCol<Account, i64>,
    pub handle: __sdk::__query_builder::IxCol<Account, String>,
    pub identity: __sdk::__query_builder::IxCol<Account, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Account {
    type IxCols = AccountIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountIxCols {
            bankroll: __sdk::__query_builder::IxCol::new(table_name, "bankroll"),
            handle: __sdk::__query_builder::IxCol::new(table_name, "handle"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Account {}
