// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BanAccountArgs {
    pub handle: String,
    pub banned: bool,
}

impl From<BanAccountArgs> for super::Reducer {
    fn from(args: BanAccountArgs) -> Self {
        Self::BanAccount {
            handle: args.handle,
            banned: args.banned,
        }
    }
}

impl __sdk::InModule for BanAccountArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ban_account`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ban_account {
    /// Request that the remote module invoke the reducer `ban_account` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ban_account:ban_account_then`] to run a callback after the reducer completes.
    fn ban_account(&self, handle: String, banned: bool) -> __sdk::Result<()> {
        self.ban_account_then(handle, banned, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ban_account` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ban_account_then(
        &self,
        handle: String,
        banned: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ban_account for super::RemoteReducers {
    fn ban_account_then(
        &self,
        handle: String,
        banned: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BanAccountArgs { handle, banned }, callback)
    }
}
