// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreditAccountArgs {
    pub handle: String,
    pub amount: i64,
}

impl From<CreditAccountArgs> for super::Reducer {
    fn from(args: CreditAccountArgs) -> Self {
        Self::CreditAccount {
            handle: args.handle,
            amount: args.amount,
        }
    }
}

impl __sdk::InModule for CreditAccountArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `credit_account`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait credit_account {
    /// Request that the remote module invoke the reducer `credit_account` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`credit_account:credit_account_then`] to run a callback after the reducer completes.
    fn credit_account(&self, handle: String, amount: i64) -> __sdk::Result<()> {
        self.credit_account_then(handle, amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `credit_account` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn credit_account_then(
        &self,
        handle: String,
        amount: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl credit_account for super::RemoteReducers {
    fn credit_account_then(
        &self,
        handle: String,
        amount: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreditAccountArgs { handle, amount }, callback)
    }
}
