// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Game {
    pub game_id: u64,
    pub name: String,
    pub created_by: __sdk::Identity,
    pub small_blind: i64,
    pub big_blind: i64,
    pub buy_in: i64,
    pub status: String,
    pub seats_taken: u32,
    pub observers: u32,
    pub hand_no: u32,
    pub pot: i64,
    pub board: String,
    pub street: String,
    pub to_act_seat: Option<u64>,
    pub current_bet: i64,
    pub starts_at: __sdk::Timestamp,
    pub created_at: __sdk::Timestamp,
    pub ended_at: Option<__sdk::Timestamp>,
    pub winner: Option<__sdk::Identity>,
    pub wait_rounds: u32,
    pub to_act_since_micros: i64,
}

impl __sdk::InModule for Game {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Game`.
///
/// Provides typed access to columns for query building.
pub struct GameCols {
    pub game_id: __sdk::__query_builder::Col<Game, u64>,
    pub name: __sdk::__query_builder::Col<Game, String>,
    pub created_by: __sdk::__query_builder::Col<Game, __sdk::Identity>,
    pub small_blind: __sdk::__query_builder::Col<Game, i64>,
    pub big_blind: __sdk::__query_builder::Col<Game, i64>,
    pub buy_in: __sdk::__query_builder::Col<Game, i64>,
    pub status: __sdk::__query_builder::Col<Game, String>,
    pub seats_taken: __sdk::__query_builder::Col<Game, u32>,
    pub observers: __sdk::__query_builder::Col<Game, u32>,
    pub hand_no: __sdk::__query_builder::Col<Game, u32>,
    pub pot: __sdk::__query_builder::Col<Game, i64>,
    pub board: __sdk::__query_builder::Col<Game, String>,
    pub street: __sdk::__query_builder::Col<Game, String>,
    pub to_act_seat: __sdk::__query_builder::Col<Game, Option<u64>>,
    pub current_bet: __sdk::__query_builder::Col<Game, i64>,
    pub starts_at: __sdk::__query_builder::Col<Game, __sdk::Timestamp>,
    pub created_at: __sdk::__query_builder::Col<Game, __sdk::Timestamp>,
    pub ended_at: __sdk::__query_builder::Col<Game, Option<__sdk::Timestamp>>,
    pub winner: __sdk::__query_builder::Col<Game, Option<__sdk::Identity>>,
    pub wait_rounds: __sdk::__query_builder::Col<Game, u32>,
    pub to_act_since_micros: __sdk::__query_builder::Col<Game, i64>,
}

impl __sdk::__query_builder::HasCols for Game {
    type Cols = GameCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameCols {
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            created_by: __sdk::__query_builder::Col::new(table_name, "created_by"),
            small_blind: __sdk::__query_builder::Col::new(table_name, "small_blind"),
            big_blind: __sdk::__query_builder::Col::new(table_name, "big_blind"),
            buy_in: __sdk::__query_builder::Col::new(table_name, "buy_in"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            seats_taken: __sdk::__query_builder::Col::new(table_name, "seats_taken"),
            observers: __sdk::__query_builder::Col::new(table_name, "observers"),
            hand_no: __sdk::__query_builder::Col::new(table_name, "hand_no"),
            pot: __sdk::__query_builder::Col::new(table_name, "pot"),
            board: __sdk::__query_builder::Col::new(table_name, "board"),
            street: __sdk::__query_builder::Col::new(table_name, "street"),
            to_act_seat: __sdk::__query_builder::Col::new(table_name, "to_act_seat"),
            current_bet: __sdk::__query_builder::Col::new(table_name, "current_bet"),
            starts_at: __sdk::__query_builder::Col::new(table_name, "starts_at"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            ended_at: __sdk::__query_builder::Col::new(table_name, "ended_at"),
            winner: __sdk::__query_builder::Col::new(table_name, "winner"),
            wait_rounds: __sdk::__query_builder::Col::new(table_name, "wait_rounds"),
            to_act_since_micros: __sdk::__query_builder::Col::new(
                table_name,
                "to_act_since_micros",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `Game`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameIxCols {
    pub game_id: __sdk::__query_builder::IxCol<Game, u64>,
    pub status: __sdk::__query_builder::IxCol<Game, String>,
}

impl __sdk::__query_builder::HasIxCols for Game {
    type IxCols = GameIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameIxCols {
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Game {}
