// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameEvent {
    pub event_id: u64,
    pub game_id: u64,
    pub seq: u32,
    pub at: __sdk::Timestamp,
    pub kind: String,
    pub handle: String,
    pub amount: i64,
    pub detail: String,
}

impl __sdk::InModule for GameEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GameEvent`.
///
/// Provides typed access to columns for query building.
pub struct GameEventCols {
    pub event_id: __sdk::__query_builder::Col<GameEvent, u64>,
    pub game_id: __sdk::__query_builder::Col<GameEvent, u64>,
    pub seq: __sdk::__query_builder::Col<GameEvent, u32>,
    pub at: __sdk::__query_builder::Col<GameEvent, __sdk::Timestamp>,
    pub kind: __sdk::__query_builder::Col<GameEvent, String>,
    pub handle: __sdk::__query_builder::Col<GameEvent, String>,
    pub amount: __sdk::__query_builder::Col<GameEvent, i64>,
    pub detail: __sdk::__query_builder::Col<GameEvent, String>,
}

impl __sdk::__query_builder::HasCols for GameEvent {
    type Cols = GameEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameEventCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            handle: __sdk::__query_builder::Col::new(table_name, "handle"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            detail: __sdk::__query_builder::Col::new(table_name, "detail"),
        }
    }
}

/// Indexed column accessor struct for the table `GameEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameEventIxCols {
    pub event_id: __sdk::__query_builder::IxCol<GameEvent, u64>,
    pub game_id: __sdk::__query_builder::IxCol<GameEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for GameEvent {
    type IxCols = GameEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameEventIxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameEvent {}
