// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HoleCards {
    pub id: u64,
    pub game_id: u64,
    pub seat_id: u64,
    pub account: __sdk::Identity,
    pub card_a: u8,
    pub card_b: u8,
}

impl __sdk::InModule for HoleCards {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HoleCards`.
///
/// Provides typed access to columns for query building.
pub struct HoleCardsCols {
    pub id: __sdk::__query_builder::Col<HoleCards, u64>,
    pub game_id: __sdk::__query_builder::Col<HoleCards, u64>,
    pub seat_id: __sdk::__query_builder::Col<HoleCards, u64>,
    pub account: __sdk::__query_builder::Col<HoleCards, __sdk::Identity>,
    pub card_a: __sdk::__query_builder::Col<HoleCards, u8>,
    pub card_b: __sdk::__query_builder::Col<HoleCards, u8>,
}

impl __sdk::__query_builder::HasCols for HoleCards {
    type Cols = HoleCardsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HoleCardsCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            seat_id: __sdk::__query_builder::Col::new(table_name, "seat_id"),
            account: __sdk::__query_builder::Col::new(table_name, "account"),
            card_a: __sdk::__query_builder::Col::new(table_name, "card_a"),
            card_b: __sdk::__query_builder::Col::new(table_name, "card_b"),
        }
    }
}

/// Indexed column accessor struct for the table `HoleCards`.
///
/// Provides typed access to indexed columns for query building.
pub struct HoleCardsIxCols {
    pub account: __sdk::__query_builder::IxCol<HoleCards, __sdk::Identity>,
    pub game_id: __sdk::__query_builder::IxCol<HoleCards, u64>,
    pub id: __sdk::__query_builder::IxCol<HoleCards, u64>,
    pub seat_id: __sdk::__query_builder::IxCol<HoleCards, u64>,
}

impl __sdk::__query_builder::HasIxCols for HoleCards {
    type IxCols = HoleCardsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HoleCardsIxCols {
            account: __sdk::__query_builder::IxCol::new(table_name, "account"),
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            seat_id: __sdk::__query_builder::IxCol::new(table_name, "seat_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HoleCards {}
