// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LedgerEntry {
    pub entry_id: u64,
    pub at: __sdk::Timestamp,
    pub account: __sdk::Identity,
    pub handle: String,
    pub kind: String,
    pub amount: i64,
    pub balance_after: i64,
    pub game_id: Option<u64>,
}

impl __sdk::InModule for LedgerEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LedgerEntry`.
///
/// Provides typed access to columns for query building.
pub struct LedgerEntryCols {
    pub entry_id: __sdk::__query_builder::Col<LedgerEntry, u64>,
    pub at: __sdk::__query_builder::Col<LedgerEntry, __sdk::Timestamp>,
    pub account: __sdk::__query_builder::Col<LedgerEntry, __sdk::Identity>,
    pub handle: __sdk::__query_builder::Col<LedgerEntry, String>,
    pub kind: __sdk::__query_builder::Col<LedgerEntry, String>,
    pub amount: __sdk::__query_builder::Col<LedgerEntry, i64>,
    pub balance_after: __sdk::__query_builder::Col<LedgerEntry, i64>,
    pub game_id: __sdk::__query_builder::Col<LedgerEntry, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for LedgerEntry {
    type Cols = LedgerEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LedgerEntryCols {
            entry_id: __sdk::__query_builder::Col::new(table_name, "entry_id"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
            account: __sdk::__query_builder::Col::new(table_name, "account"),
            handle: __sdk::__query_builder::Col::new(table_name, "handle"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            balance_after: __sdk::__query_builder::Col::new(table_name, "balance_after"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
        }
    }
}

/// Indexed column accessor struct for the table `LedgerEntry`.
///
/// Provides typed access to indexed columns for query building.
pub struct LedgerEntryIxCols {
    pub account: __sdk::__query_builder::IxCol<LedgerEntry, __sdk::Identity>,
    pub entry_id: __sdk::__query_builder::IxCol<LedgerEntry, u64>,
}

impl __sdk::__query_builder::HasIxCols for LedgerEntry {
    type IxCols = LedgerEntryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LedgerEntryIxCols {
            account: __sdk::__query_builder::IxCol::new(table_name, "account"),
            entry_id: __sdk::__query_builder::IxCol::new(table_name, "entry_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LedgerEntry {}
