// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ledger_entry_type::LedgerEntry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ledger`.
///
/// Obtain a handle from the [`LedgerTableAccess::ledger`] method on [`super::RemoteTables`],
/// like `ctx.db.ledger()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ledger().on_insert(...)`.
pub struct LedgerTableHandle<'ctx> {
    imp: __sdk::TableHandle<LedgerEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `ledger`.
pub struct LedgerTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for LedgerTableAccessor {
    type Row = LedgerEntry;
    type Handle<'db> = LedgerTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.ledger()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ledger`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LedgerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LedgerTableHandle`], which mediates access to the table `ledger`.
    fn ledger(&self) -> LedgerTableHandle<'_>;
}

impl LedgerTableAccess for super::RemoteTables {
    fn ledger(&self) -> LedgerTableHandle<'_> {
        LedgerTableHandle {
            imp: self.imp.get_table::<LedgerEntry>("ledger"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LedgerInsertCallbackId(__sdk::CallbackId);
pub struct LedgerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for LedgerTableHandle<'ctx> {
    type Row = LedgerEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LedgerEntry> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for LedgerTableHandle<'ctx> {
    type Row = LedgerEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LedgerEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LedgerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LedgerInsertCallbackId {
        LedgerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LedgerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LedgerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LedgerDeleteCallbackId {
        LedgerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LedgerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for LedgerTableHandle<'ctx> {
    type InsertCallbackId = LedgerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LedgerInsertCallbackId {
        LedgerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LedgerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for LedgerTableHandle<'ctx> {
    type DeleteCallbackId = LedgerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LedgerDeleteCallbackId {
        LedgerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LedgerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LedgerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LedgerTableHandle<'ctx> {
    type UpdateCallbackId = LedgerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LedgerUpdateCallbackId {
        LedgerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LedgerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for LedgerTableHandle<'ctx> {
    type UpdateCallbackId = LedgerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LedgerUpdateCallbackId {
        LedgerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LedgerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entry_id` unique index on the table `ledger`,
/// which allows point queries on the field of the same name
/// via the [`LedgerEntryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ledger().entry_id().find(...)`.
pub struct LedgerEntryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LedgerEntry, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LedgerTableHandle<'ctx> {
    /// Get a handle on the `entry_id` unique index on the table `ledger`.
    pub fn entry_id(&self) -> LedgerEntryIdUnique<'ctx> {
        LedgerEntryIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entry_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LedgerEntryIdUnique<'ctx> {
    /// Find the subscribed row whose `entry_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LedgerEntry> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LedgerEntry>("ledger");
    _table.add_unique_constraint::<u64>("entry_id", |row| &row.entry_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LedgerEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LedgerEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LedgerEntry`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ledgerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LedgerEntry`.
    fn ledger(&self) -> __sdk::__query_builder::Table<LedgerEntry>;
}

impl ledgerQueryTableAccess for __sdk::QueryTableAccessor {
    fn ledger(&self) -> __sdk::__query_builder::Table<LedgerEntry> {
        __sdk::__query_builder::Table::new("ledger")
    }
}
