// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.7.0 (commit d8be729d2c7214659c3b8d267efbd806a62fc378).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod account_table;
pub mod account_type;
pub mod act_reducer;
pub mod ban_account_reducer;
pub mod close_game_reducer;
pub mod config_table;
pub mod config_type;
pub mod create_game_reducer;
pub mod credit_account_reducer;
pub mod game_event_table;
pub mod game_event_type;
pub mod game_table;
pub mod game_type;
pub mod hole_cards_type;
pub mod join_game_reducer;
pub mod leave_game_reducer;
pub mod ledger_entry_type;
pub mod ledger_table;
pub mod my_hole_cards_table;
pub mod observe_game_reducer;
pub mod observer_table;
pub mod observer_type;
pub mod player_ranking_type;
pub mod register_reducer;
pub mod seat_table;
pub mod seat_type;
pub mod set_config_reducer;
pub mod start_timer_type;
pub mod stop_observing_reducer;
pub mod top_players_table;
pub mod turn_timer_type;

pub use account_table::*;
pub use account_type::Account;
pub use act_reducer::act;
pub use ban_account_reducer::ban_account;
pub use close_game_reducer::close_game;
pub use config_table::*;
pub use config_type::Config;
pub use create_game_reducer::create_game;
pub use credit_account_reducer::credit_account;
pub use game_event_table::*;
pub use game_event_type::GameEvent;
pub use game_table::*;
pub use game_type::Game;
pub use hole_cards_type::HoleCards;
pub use join_game_reducer::join_game;
pub use leave_game_reducer::leave_game;
pub use ledger_entry_type::LedgerEntry;
pub use ledger_table::*;
pub use my_hole_cards_table::*;
pub use observe_game_reducer::observe_game;
pub use observer_table::*;
pub use observer_type::Observer;
pub use player_ranking_type::PlayerRanking;
pub use register_reducer::register;
pub use seat_table::*;
pub use seat_type::Seat;
pub use set_config_reducer::set_config;
pub use start_timer_type::StartTimer;
pub use stop_observing_reducer::stop_observing;
pub use top_players_table::*;
pub use turn_timer_type::TurnTimer;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    Act {
        action: String,
        amount: i64,
    },
    BanAccount {
        handle: String,
        banned: bool,
    },
    CloseGame {
        game_id: u64,
    },
    CreateGame {
        name: String,
        small_blind: i64,
        buy_in: i64,
    },
    CreditAccount {
        handle: String,
        amount: i64,
    },
    JoinGame {
        game_id: u64,
    },
    LeaveGame,
    ObserveGame {
        game_id: u64,
    },
    Register {
        handle: String,
    },
    SetConfig {
        starting_capital: i64,
        join_window_secs: u64,
        turn_timeout_secs: u64,
    },
    StopObserving {
        game_id: u64,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::Act { .. } => "act",
            Reducer::BanAccount { .. } => "ban_account",
            Reducer::CloseGame { .. } => "close_game",
            Reducer::CreateGame { .. } => "create_game",
            Reducer::CreditAccount { .. } => "credit_account",
            Reducer::JoinGame { .. } => "join_game",
            Reducer::LeaveGame => "leave_game",
            Reducer::ObserveGame { .. } => "observe_game",
            Reducer::Register { .. } => "register",
            Reducer::SetConfig { .. } => "set_config",
            Reducer::StopObserving { .. } => "stop_observing",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::Act { action, amount } => __sats::bsatn::to_vec(&act_reducer::ActArgs {
                action: action.clone(),
                amount: amount.clone(),
            }),
            Reducer::BanAccount { handle, banned } => {
                __sats::bsatn::to_vec(&ban_account_reducer::BanAccountArgs {
                    handle: handle.clone(),
                    banned: banned.clone(),
                })
            }
            Reducer::CloseGame { game_id } => {
                __sats::bsatn::to_vec(&close_game_reducer::CloseGameArgs {
                    game_id: game_id.clone(),
                })
            }
            Reducer::CreateGame {
                name,
                small_blind,
                buy_in,
            } => __sats::bsatn::to_vec(&create_game_reducer::CreateGameArgs {
                name: name.clone(),
                small_blind: small_blind.clone(),
                buy_in: buy_in.clone(),
            }),
            Reducer::CreditAccount { handle, amount } => {
                __sats::bsatn::to_vec(&credit_account_reducer::CreditAccountArgs {
                    handle: handle.clone(),
                    amount: amount.clone(),
                })
            }
            Reducer::JoinGame { game_id } => {
                __sats::bsatn::to_vec(&join_game_reducer::JoinGameArgs {
                    game_id: game_id.clone(),
                })
            }
            Reducer::LeaveGame => __sats::bsatn::to_vec(&leave_game_reducer::LeaveGameArgs {}),
            Reducer::ObserveGame { game_id } => {
                __sats::bsatn::to_vec(&observe_game_reducer::ObserveGameArgs {
                    game_id: game_id.clone(),
                })
            }
            Reducer::Register { handle } => {
                __sats::bsatn::to_vec(&register_reducer::RegisterArgs {
                    handle: handle.clone(),
                })
            }
            Reducer::SetConfig {
                starting_capital,
                join_window_secs,
                turn_timeout_secs,
            } => __sats::bsatn::to_vec(&set_config_reducer::SetConfigArgs {
                starting_capital: starting_capital.clone(),
                join_window_secs: join_window_secs.clone(),
                turn_timeout_secs: turn_timeout_secs.clone(),
            }),
            Reducer::StopObserving { game_id } => {
                __sats::bsatn::to_vec(&stop_observing_reducer::StopObservingArgs {
                    game_id: game_id.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    account: __sdk::TableUpdate<Account>,
    config: __sdk::TableUpdate<Config>,
    game: __sdk::TableUpdate<Game>,
    game_event: __sdk::TableUpdate<GameEvent>,
    ledger: __sdk::TableUpdate<LedgerEntry>,
    my_hole_cards: __sdk::TableUpdate<HoleCards>,
    observer: __sdk::TableUpdate<Observer>,
    seat: __sdk::TableUpdate<Seat>,
    top_players: __sdk::TableUpdate<PlayerRanking>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "account" => db_update
                    .account
                    .append(account_table::parse_table_update(table_update)?),
                "config" => db_update
                    .config
                    .append(config_table::parse_table_update(table_update)?),
                "game" => db_update
                    .game
                    .append(game_table::parse_table_update(table_update)?),
                "game_event" => db_update
                    .game_event
                    .append(game_event_table::parse_table_update(table_update)?),
                "ledger" => db_update
                    .ledger
                    .append(ledger_table::parse_table_update(table_update)?),
                "my_hole_cards" => db_update
                    .my_hole_cards
                    .append(my_hole_cards_table::parse_table_update(table_update)?),
                "observer" => db_update
                    .observer
                    .append(observer_table::parse_table_update(table_update)?),
                "seat" => db_update
                    .seat
                    .append(seat_table::parse_table_update(table_update)?),
                "top_players" => db_update
                    .top_players
                    .append(top_players_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.account = cache
            .apply_diff_to_table::<Account>("account", &self.account)
            .with_updates_by_pk(|row| &row.identity);
        diff.config = cache
            .apply_diff_to_table::<Config>("config", &self.config)
            .with_updates_by_pk(|row| &row.id);
        diff.game = cache
            .apply_diff_to_table::<Game>("game", &self.game)
            .with_updates_by_pk(|row| &row.game_id);
        diff.game_event = cache
            .apply_diff_to_table::<GameEvent>("game_event", &self.game_event)
            .with_updates_by_pk(|row| &row.event_id);
        diff.ledger = cache
            .apply_diff_to_table::<LedgerEntry>("ledger", &self.ledger)
            .with_updates_by_pk(|row| &row.entry_id);
        diff.observer = cache
            .apply_diff_to_table::<Observer>("observer", &self.observer)
            .with_updates_by_pk(|row| &row.observer_id);
        diff.seat = cache
            .apply_diff_to_table::<Seat>("seat", &self.seat)
            .with_updates_by_pk(|row| &row.seat_id);
        diff.my_hole_cards =
            cache.apply_diff_to_table::<HoleCards>("my_hole_cards", &self.my_hole_cards);
        diff.top_players =
            cache.apply_diff_to_table::<PlayerRanking>("top_players", &self.top_players);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "account" => db_update
                    .account
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "config" => db_update
                    .config
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game" => db_update
                    .game
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_event" => db_update
                    .game_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ledger" => db_update
                    .ledger
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_hole_cards" => db_update
                    .my_hole_cards
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "observer" => db_update
                    .observer
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "seat" => db_update
                    .seat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "top_players" => db_update
                    .top_players
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "account" => db_update
                    .account
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "config" => db_update
                    .config
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game" => db_update
                    .game
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_event" => db_update
                    .game_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ledger" => db_update
                    .ledger
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_hole_cards" => db_update
                    .my_hole_cards
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "observer" => db_update
                    .observer
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "seat" => db_update
                    .seat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "top_players" => db_update
                    .top_players
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    account: __sdk::TableAppliedDiff<'r, Account>,
    config: __sdk::TableAppliedDiff<'r, Config>,
    game: __sdk::TableAppliedDiff<'r, Game>,
    game_event: __sdk::TableAppliedDiff<'r, GameEvent>,
    ledger: __sdk::TableAppliedDiff<'r, LedgerEntry>,
    my_hole_cards: __sdk::TableAppliedDiff<'r, HoleCards>,
    observer: __sdk::TableAppliedDiff<'r, Observer>,
    seat: __sdk::TableAppliedDiff<'r, Seat>,
    top_players: __sdk::TableAppliedDiff<'r, PlayerRanking>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Account>("account", &self.account, event);
        callbacks.invoke_table_row_callbacks::<Config>("config", &self.config, event);
        callbacks.invoke_table_row_callbacks::<Game>("game", &self.game, event);
        callbacks.invoke_table_row_callbacks::<GameEvent>("game_event", &self.game_event, event);
        callbacks.invoke_table_row_callbacks::<LedgerEntry>("ledger", &self.ledger, event);
        callbacks.invoke_table_row_callbacks::<HoleCards>(
            "my_hole_cards",
            &self.my_hole_cards,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Observer>("observer", &self.observer, event);
        callbacks.invoke_table_row_callbacks::<Seat>("seat", &self.seat, event);
        callbacks.invoke_table_row_callbacks::<PlayerRanking>(
            "top_players",
            &self.top_players,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        account_table::register_table(client_cache);
        config_table::register_table(client_cache);
        game_table::register_table(client_cache);
        game_event_table::register_table(client_cache);
        ledger_table::register_table(client_cache);
        my_hole_cards_table::register_table(client_cache);
        observer_table::register_table(client_cache);
        seat_table::register_table(client_cache);
        top_players_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "account",
        "config",
        "game",
        "game_event",
        "ledger",
        "my_hole_cards",
        "observer",
        "seat",
        "top_players",
    ];
}
