// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hole_cards_type::HoleCards;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_hole_cards`.
///
/// Obtain a handle from the [`MyHoleCardsTableAccess::my_hole_cards`] method on [`super::RemoteTables`],
/// like `ctx.db.my_hole_cards()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_hole_cards().on_insert(...)`.
pub struct MyHoleCardsTableHandle<'ctx> {
    imp: __sdk::TableHandle<HoleCards>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_hole_cards`.
pub struct MyHoleCardsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyHoleCardsTableAccessor {
    type Row = HoleCards;
    type Handle<'db> = MyHoleCardsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_hole_cards()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_hole_cards`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyHoleCardsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyHoleCardsTableHandle`], which mediates access to the table `my_hole_cards`.
    fn my_hole_cards(&self) -> MyHoleCardsTableHandle<'_>;
}

impl MyHoleCardsTableAccess for super::RemoteTables {
    fn my_hole_cards(&self) -> MyHoleCardsTableHandle<'_> {
        MyHoleCardsTableHandle {
            imp: self.imp.get_table::<HoleCards>("my_hole_cards"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyHoleCardsInsertCallbackId(__sdk::CallbackId);
pub struct MyHoleCardsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyHoleCardsTableHandle<'ctx> {
    type Row = HoleCards;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HoleCards> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyHoleCardsTableHandle<'ctx> {
    type Row = HoleCards;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HoleCards> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyHoleCardsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHoleCardsInsertCallbackId {
        MyHoleCardsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyHoleCardsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyHoleCardsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHoleCardsDeleteCallbackId {
        MyHoleCardsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyHoleCardsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyHoleCardsTableHandle<'ctx> {
    type InsertCallbackId = MyHoleCardsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHoleCardsInsertCallbackId {
        MyHoleCardsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyHoleCardsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyHoleCardsTableHandle<'ctx> {
    type DeleteCallbackId = MyHoleCardsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHoleCardsDeleteCallbackId {
        MyHoleCardsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyHoleCardsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<HoleCards>("my_hole_cards");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HoleCards>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HoleCards>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HoleCards`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_hole_cardsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HoleCards`.
    fn my_hole_cards(&self) -> __sdk::__query_builder::Table<HoleCards>;
}

impl my_hole_cardsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_hole_cards(&self) -> __sdk::__query_builder::Table<HoleCards> {
        __sdk::__query_builder::Table::new("my_hole_cards")
    }
}
