// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Observer {
    pub observer_id: u64,
    pub game_id: u64,
    pub account: __sdk::Identity,
    pub handle: String,
    pub since: __sdk::Timestamp,
}

impl __sdk::InModule for Observer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Observer`.
///
/// Provides typed access to columns for query building.
pub struct ObserverCols {
    pub observer_id: __sdk::__query_builder::Col<Observer, u64>,
    pub game_id: __sdk::__query_builder::Col<Observer, u64>,
    pub account: __sdk::__query_builder::Col<Observer, __sdk::Identity>,
    pub handle: __sdk::__query_builder::Col<Observer, String>,
    pub since: __sdk::__query_builder::Col<Observer, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Observer {
    type Cols = ObserverCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ObserverCols {
            observer_id: __sdk::__query_builder::Col::new(table_name, "observer_id"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            account: __sdk::__query_builder::Col::new(table_name, "account"),
            handle: __sdk::__query_builder::Col::new(table_name, "handle"),
            since: __sdk::__query_builder::Col::new(table_name, "since"),
        }
    }
}

/// Indexed column accessor struct for the table `Observer`.
///
/// Provides typed access to indexed columns for query building.
pub struct ObserverIxCols {
    pub game_id: __sdk::__query_builder::IxCol<Observer, u64>,
    pub observer_id: __sdk::__query_builder::IxCol<Observer, u64>,
}

impl __sdk::__query_builder::HasIxCols for Observer {
    type IxCols = ObserverIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ObserverIxCols {
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
            observer_id: __sdk::__query_builder::IxCol::new(table_name, "observer_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Observer {}
