// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ObserveGameArgs {
    pub game_id: u64,
}

impl From<ObserveGameArgs> for super::Reducer {
    fn from(args: ObserveGameArgs) -> Self {
        Self::ObserveGame {
            game_id: args.game_id,
        }
    }
}

impl __sdk::InModule for ObserveGameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `observe_game`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait observe_game {
    /// Request that the remote module invoke the reducer `observe_game` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`observe_game:observe_game_then`] to run a callback after the reducer completes.
    fn observe_game(&self, game_id: u64) -> __sdk::Result<()> {
        self.observe_game_then(game_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `observe_game` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn observe_game_then(
        &self,
        game_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl observe_game for super::RemoteReducers {
    fn observe_game_then(
        &self,
        game_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ObserveGameArgs { game_id }, callback)
    }
}
