// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::observer_type::Observer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `observer`.
///
/// Obtain a handle from the [`ObserverTableAccess::observer`] method on [`super::RemoteTables`],
/// like `ctx.db.observer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.observer().on_insert(...)`.
pub struct ObserverTableHandle<'ctx> {
    imp: __sdk::TableHandle<Observer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `observer`.
pub struct ObserverTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ObserverTableAccessor {
    type Row = Observer;
    type Handle<'db> = ObserverTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.observer()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `observer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ObserverTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ObserverTableHandle`], which mediates access to the table `observer`.
    fn observer(&self) -> ObserverTableHandle<'_>;
}

impl ObserverTableAccess for super::RemoteTables {
    fn observer(&self) -> ObserverTableHandle<'_> {
        ObserverTableHandle {
            imp: self.imp.get_table::<Observer>("observer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ObserverInsertCallbackId(__sdk::CallbackId);
pub struct ObserverDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ObserverTableHandle<'ctx> {
    type Row = Observer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Observer> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ObserverTableHandle<'ctx> {
    type Row = Observer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Observer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ObserverInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ObserverInsertCallbackId {
        ObserverInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ObserverInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ObserverDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ObserverDeleteCallbackId {
        ObserverDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ObserverDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ObserverTableHandle<'ctx> {
    type InsertCallbackId = ObserverInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ObserverInsertCallbackId {
        ObserverInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ObserverInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ObserverTableHandle<'ctx> {
    type DeleteCallbackId = ObserverDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ObserverDeleteCallbackId {
        ObserverDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ObserverDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ObserverUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ObserverTableHandle<'ctx> {
    type UpdateCallbackId = ObserverUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ObserverUpdateCallbackId {
        ObserverUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ObserverUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ObserverTableHandle<'ctx> {
    type UpdateCallbackId = ObserverUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ObserverUpdateCallbackId {
        ObserverUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ObserverUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `observer_id` unique index on the table `observer`,
/// which allows point queries on the field of the same name
/// via the [`ObserverObserverIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.observer().observer_id().find(...)`.
pub struct ObserverObserverIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Observer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ObserverTableHandle<'ctx> {
    /// Get a handle on the `observer_id` unique index on the table `observer`.
    pub fn observer_id(&self) -> ObserverObserverIdUnique<'ctx> {
        ObserverObserverIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("observer_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ObserverObserverIdUnique<'ctx> {
    /// Find the subscribed row whose `observer_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Observer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Observer>("observer");
    _table.add_unique_constraint::<u64>("observer_id", |row| &row.observer_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Observer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Observer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Observer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait observerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Observer`.
    fn observer(&self) -> __sdk::__query_builder::Table<Observer>;
}

impl observerQueryTableAccess for __sdk::QueryTableAccessor {
    fn observer(&self) -> __sdk::__query_builder::Table<Observer> {
        __sdk::__query_builder::Table::new("observer")
    }
}
