// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerRanking {
    pub handle: String,
    pub identity: __sdk::Identity,
    pub bankroll: i64,
    pub net: i64,
    pub games_played: u32,
    pub games_won: u32,
}

impl __sdk::InModule for PlayerRanking {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerRanking`.
///
/// Provides typed access to columns for query building.
pub struct PlayerRankingCols {
    pub handle: __sdk::__query_builder::Col<PlayerRanking, String>,
    pub identity: __sdk::__query_builder::Col<PlayerRanking, __sdk::Identity>,
    pub bankroll: __sdk::__query_builder::Col<PlayerRanking, i64>,
    pub net: __sdk::__query_builder::Col<PlayerRanking, i64>,
    pub games_played: __sdk::__query_builder::Col<PlayerRanking, u32>,
    pub games_won: __sdk::__query_builder::Col<PlayerRanking, u32>,
}

impl __sdk::__query_builder::HasCols for PlayerRanking {
    type Cols = PlayerRankingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerRankingCols {
            handle: __sdk::__query_builder::Col::new(table_name, "handle"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            bankroll: __sdk::__query_builder::Col::new(table_name, "bankroll"),
            net: __sdk::__query_builder::Col::new(table_name, "net"),
            games_played: __sdk::__query_builder::Col::new(table_name, "games_played"),
            games_won: __sdk::__query_builder::Col::new(table_name, "games_won"),
        }
    }
}
