// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Seat {
    pub seat_id: u64,
    pub game_id: u64,
    pub seat_no: u32,
    pub account: __sdk::Identity,
    pub handle: String,
    pub chips: i64,
    pub committed: i64,
    pub state: String,
    pub joined_at: __sdk::Timestamp,
}

impl __sdk::InModule for Seat {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Seat`.
///
/// Provides typed access to columns for query building.
pub struct SeatCols {
    pub seat_id: __sdk::__query_builder::Col<Seat, u64>,
    pub game_id: __sdk::__query_builder::Col<Seat, u64>,
    pub seat_no: __sdk::__query_builder::Col<Seat, u32>,
    pub account: __sdk::__query_builder::Col<Seat, __sdk::Identity>,
    pub handle: __sdk::__query_builder::Col<Seat, String>,
    pub chips: __sdk::__query_builder::Col<Seat, i64>,
    pub committed: __sdk::__query_builder::Col<Seat, i64>,
    pub state: __sdk::__query_builder::Col<Seat, String>,
    pub joined_at: __sdk::__query_builder::Col<Seat, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Seat {
    type Cols = SeatCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SeatCols {
            seat_id: __sdk::__query_builder::Col::new(table_name, "seat_id"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            seat_no: __sdk::__query_builder::Col::new(table_name, "seat_no"),
            account: __sdk::__query_builder::Col::new(table_name, "account"),
            handle: __sdk::__query_builder::Col::new(table_name, "handle"),
            chips: __sdk::__query_builder::Col::new(table_name, "chips"),
            committed: __sdk::__query_builder::Col::new(table_name, "committed"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            joined_at: __sdk::__query_builder::Col::new(table_name, "joined_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Seat`.
///
/// Provides typed access to indexed columns for query building.
pub struct SeatIxCols {
    pub account: __sdk::__query_builder::IxCol<Seat, __sdk::Identity>,
    pub game_id: __sdk::__query_builder::IxCol<Seat, u64>,
    pub seat_id: __sdk::__query_builder::IxCol<Seat, u64>,
}

impl __sdk::__query_builder::HasIxCols for Seat {
    type IxCols = SeatIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SeatIxCols {
            account: __sdk::__query_builder::IxCol::new(table_name, "account"),
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
            seat_id: __sdk::__query_builder::IxCol::new(table_name, "seat_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Seat {}
