// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::seat_type::Seat;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `seat`.
///
/// Obtain a handle from the [`SeatTableAccess::seat`] method on [`super::RemoteTables`],
/// like `ctx.db.seat()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.seat().on_insert(...)`.
pub struct SeatTableHandle<'ctx> {
    imp: __sdk::TableHandle<Seat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `seat`.
pub struct SeatTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SeatTableAccessor {
    type Row = Seat;
    type Handle<'db> = SeatTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.seat()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `seat`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SeatTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SeatTableHandle`], which mediates access to the table `seat`.
    fn seat(&self) -> SeatTableHandle<'_>;
}

impl SeatTableAccess for super::RemoteTables {
    fn seat(&self) -> SeatTableHandle<'_> {
        SeatTableHandle {
            imp: self.imp.get_table::<Seat>("seat"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SeatInsertCallbackId(__sdk::CallbackId);
pub struct SeatDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SeatTableHandle<'ctx> {
    type Row = Seat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Seat> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SeatTableHandle<'ctx> {
    type Row = Seat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Seat> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SeatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SeatInsertCallbackId {
        SeatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SeatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SeatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SeatDeleteCallbackId {
        SeatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SeatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SeatTableHandle<'ctx> {
    type InsertCallbackId = SeatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SeatInsertCallbackId {
        SeatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SeatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SeatTableHandle<'ctx> {
    type DeleteCallbackId = SeatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SeatDeleteCallbackId {
        SeatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SeatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SeatUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SeatTableHandle<'ctx> {
    type UpdateCallbackId = SeatUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SeatUpdateCallbackId {
        SeatUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SeatUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SeatTableHandle<'ctx> {
    type UpdateCallbackId = SeatUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SeatUpdateCallbackId {
        SeatUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SeatUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `seat_id` unique index on the table `seat`,
/// which allows point queries on the field of the same name
/// via the [`SeatSeatIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.seat().seat_id().find(...)`.
pub struct SeatSeatIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Seat, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SeatTableHandle<'ctx> {
    /// Get a handle on the `seat_id` unique index on the table `seat`.
    pub fn seat_id(&self) -> SeatSeatIdUnique<'ctx> {
        SeatSeatIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("seat_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SeatSeatIdUnique<'ctx> {
    /// Find the subscribed row whose `seat_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Seat> {
        self.imp.find(col_val)
    }
}

/// Access to the `account` unique index on the table `seat`,
/// which allows point queries on the field of the same name
/// via the [`SeatAccountUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.seat().account().find(...)`.
pub struct SeatAccountUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Seat, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SeatTableHandle<'ctx> {
    /// Get a handle on the `account` unique index on the table `seat`.
    pub fn account(&self) -> SeatAccountUnique<'ctx> {
        SeatAccountUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("account"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SeatAccountUnique<'ctx> {
    /// Find the subscribed row whose `account` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Seat> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Seat>("seat");
    _table.add_unique_constraint::<u64>("seat_id", |row| &row.seat_id);
    _table.add_unique_constraint::<__sdk::Identity>("account", |row| &row.account);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Seat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Seat>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Seat`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait seatQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Seat`.
    fn seat(&self) -> __sdk::__query_builder::Table<Seat>;
}

impl seatQueryTableAccess for __sdk::QueryTableAccessor {
    fn seat(&self) -> __sdk::__query_builder::Table<Seat> {
        __sdk::__query_builder::Table::new("seat")
    }
}
