// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetConfigArgs {
    pub starting_capital: i64,
    pub join_window_secs: u64,
    pub turn_timeout_secs: u64,
}

impl From<SetConfigArgs> for super::Reducer {
    fn from(args: SetConfigArgs) -> Self {
        Self::SetConfig {
            starting_capital: args.starting_capital,
            join_window_secs: args.join_window_secs,
            turn_timeout_secs: args.turn_timeout_secs,
        }
    }
}

impl __sdk::InModule for SetConfigArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_config`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_config {
    /// Request that the remote module invoke the reducer `set_config` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_config:set_config_then`] to run a callback after the reducer completes.
    fn set_config(
        &self,
        starting_capital: i64,
        join_window_secs: u64,
        turn_timeout_secs: u64,
    ) -> __sdk::Result<()> {
        self.set_config_then(
            starting_capital,
            join_window_secs,
            turn_timeout_secs,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_config` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_config_then(
        &self,
        starting_capital: i64,
        join_window_secs: u64,
        turn_timeout_secs: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_config for super::RemoteReducers {
    fn set_config_then(
        &self,
        starting_capital: i64,
        join_window_secs: u64,
        turn_timeout_secs: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetConfigArgs {
                starting_capital,
                join_window_secs,
                turn_timeout_secs,
            },
            callback,
        )
    }
}
