// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StartTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub game_id: u64,
}

impl __sdk::InModule for StartTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StartTimer`.
///
/// Provides typed access to columns for query building.
pub struct StartTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<StartTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<StartTimer, __sdk::ScheduleAt>,
    pub game_id: __sdk::__query_builder::Col<StartTimer, u64>,
}

impl __sdk::__query_builder::HasCols for StartTimer {
    type Cols = StartTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StartTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
        }
    }
}

/// Indexed column accessor struct for the table `StartTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct StartTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<StartTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for StartTimer {
    type IxCols = StartTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StartTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StartTimer {}
