// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StopObservingArgs {
    pub game_id: u64,
}

impl From<StopObservingArgs> for super::Reducer {
    fn from(args: StopObservingArgs) -> Self {
        Self::StopObserving {
            game_id: args.game_id,
        }
    }
}

impl __sdk::InModule for StopObservingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stop_observing`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stop_observing {
    /// Request that the remote module invoke the reducer `stop_observing` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stop_observing:stop_observing_then`] to run a callback after the reducer completes.
    fn stop_observing(&self, game_id: u64) -> __sdk::Result<()> {
        self.stop_observing_then(game_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `stop_observing` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stop_observing_then(
        &self,
        game_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl stop_observing for super::RemoteReducers {
    fn stop_observing_then(
        &self,
        game_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(StopObservingArgs { game_id }, callback)
    }
}
