// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_ranking_type::PlayerRanking;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `top_players`.
///
/// Obtain a handle from the [`TopPlayersTableAccess::top_players`] method on [`super::RemoteTables`],
/// like `ctx.db.top_players()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.top_players().on_insert(...)`.
pub struct TopPlayersTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerRanking>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `top_players`.
pub struct TopPlayersTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TopPlayersTableAccessor {
    type Row = PlayerRanking;
    type Handle<'db> = TopPlayersTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.top_players()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `top_players`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TopPlayersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TopPlayersTableHandle`], which mediates access to the table `top_players`.
    fn top_players(&self) -> TopPlayersTableHandle<'_>;
}

impl TopPlayersTableAccess for super::RemoteTables {
    fn top_players(&self) -> TopPlayersTableHandle<'_> {
        TopPlayersTableHandle {
            imp: self.imp.get_table::<PlayerRanking>("top_players"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TopPlayersInsertCallbackId(__sdk::CallbackId);
pub struct TopPlayersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TopPlayersTableHandle<'ctx> {
    type Row = PlayerRanking;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerRanking> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TopPlayersTableHandle<'ctx> {
    type Row = PlayerRanking;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerRanking> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TopPlayersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TopPlayersInsertCallbackId {
        TopPlayersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TopPlayersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TopPlayersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TopPlayersDeleteCallbackId {
        TopPlayersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TopPlayersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TopPlayersTableHandle<'ctx> {
    type InsertCallbackId = TopPlayersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TopPlayersInsertCallbackId {
        TopPlayersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TopPlayersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TopPlayersTableHandle<'ctx> {
    type DeleteCallbackId = TopPlayersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TopPlayersDeleteCallbackId {
        TopPlayersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TopPlayersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerRanking>("top_players");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerRanking>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerRanking>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerRanking`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait top_playersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerRanking`.
    fn top_players(&self) -> __sdk::__query_builder::Table<PlayerRanking>;
}

impl top_playersQueryTableAccess for __sdk::QueryTableAccessor {
    fn top_players(&self) -> __sdk::__query_builder::Table<PlayerRanking> {
        __sdk::__query_builder::Table::new("top_players")
    }
}
