// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TurnTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub game_id: u64,
    pub seat_id: u64,
    pub hand_no: u32,
}

impl __sdk::InModule for TurnTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TurnTimer`.
///
/// Provides typed access to columns for query building.
pub struct TurnTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<TurnTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<TurnTimer, __sdk::ScheduleAt>,
    pub game_id: __sdk::__query_builder::Col<TurnTimer, u64>,
    pub seat_id: __sdk::__query_builder::Col<TurnTimer, u64>,
    pub hand_no: __sdk::__query_builder::Col<TurnTimer, u32>,
}

impl __sdk::__query_builder::HasCols for TurnTimer {
    type Cols = TurnTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TurnTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            seat_id: __sdk::__query_builder::Col::new(table_name, "seat_id"),
            hand_no: __sdk::__query_builder::Col::new(table_name, "hand_no"),
        }
    }
}

/// Indexed column accessor struct for the table `TurnTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct TurnTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<TurnTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for TurnTimer {
    type IxCols = TurnTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TurnTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TurnTimer {}
