#!/usr/bin/env python3
"""Build the gold layer: changelog_entry rows + a draft changelog.md.

Per app release, turns assigned PRs and dependency bumps into structured,
rewrite-ready entries:
  feature | fix | deps | other
and emits data/changelog.md as a starting point for the human/AI rewrite
(the repo's CHANGELOG.md header documents the target voice).

Run transform.py first.
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config
import lib

FIX_RE = re.compile(r"\b(fix|bug)\b", re.I)
FEAT_RE = re.compile(r"\b(feat|add|new|support|improve)\b", re.I)
SKIP_LABELS = {"skip-changelog", "skip changelog"}


def classify(pr) -> str:
    try:
        labels = json.loads(pr["labels"] or "[]")
    except ValueError:
        labels = []
    hay = f"{' '.join(labels)} {pr['title']}"
    if FIX_RE.search(hay) and not FEAT_RE.search(hay):
        return "fix"
    if FEAT_RE.search(hay):
        return "feature"
    return "other"


def entry_text(pr) -> str:
    author = f" ({pr['author']})" if pr["author"] else ""
    return f"#{pr['number']} {pr['title']}{author}"


def main() -> int:
    md = ["<!-- DRAFT - generated by build_changelog.py; edit before publishing -->", ""]

    with lib.Run("build_changelog") as con:
        releases = sorted(
            con.execute(
                "SELECT r.id, r.version, r.status, r.published_at FROM release_ r"
                " JOIN package p ON p.id = r.package_id WHERE p.name = ?",
                (config.APP_CRATE,)).fetchall(),
            key=lambda r: lib.version_key(r["version"]), reverse=True)

        for rel in releases:
            con.execute("DELETE FROM changelog_entry WHERE release_id=?", (rel["id"],))
            pos = 0

            def add(kind: str, text: str, pr_id=None):
                nonlocal pos
                con.execute(
                    "INSERT INTO changelog_entry (release_id, kind, text, source_pr_id, position)"
                    " VALUES (?, ?, ?, ?, ?)",
                    (rel["id"], kind, text, pr_id, pos))
                pos += 1

            for pr in con.execute(
                    "SELECT * FROM pull_request WHERE release_id=? ORDER BY merged_at",
                    (rel["id"],)).fetchall():
                if pr["bumps_version"]:
                    continue  # the release PR itself is not changelog content
                try:
                    labels = json.loads(pr["labels"] or "[]")
                except ValueError:
                    labels = []
                if SKIP_LABELS & {str(l).lower() for l in labels}:
                    continue
                add(classify(pr), entry_text(pr), pr["id"])

            for b in con.execute(
                    "SELECT b.from_version, b.to_version, p.name FROM dependency_bump b"
                    " JOIN package p ON p.id = b.dep_package_id WHERE b.release_id=?",
                    (rel["id"],)).fetchall():
                frm = f"{b['from_version']} -> " if b["from_version"] else ""
                add("deps", f"{b['name']}: {frm}{b['to_version']}")

            date = (rel["published_at"] or "")[:10]
            suffix = "" if rel["status"] == "published" else f" ({rel['status']})"
            md.append(f"## {config.APP_CRATE} {rel['version']}{suffix}  {date}")
            for kind, header in (("feature", "What's new"), ("fix", "Fixes"),
                                 ("deps", "Dependencies"), ("other", "Other")):
                rows = con.execute(
                    "SELECT text FROM changelog_entry WHERE release_id=? AND kind=?"
                    " ORDER BY position", (rel["id"], kind)).fetchall()
                if rows:
                    md.append(f"\n### {header}\n")
                    md.extend(f"- {r['text']}" for r in rows)
            md.append("")

        con.commit()
        out = lib.DATA_DIR / "changelog.md"
        out.write_text("\n".join(md).rstrip() + "\n")
        print(f"{out}")
        print(f"changelog_entry: {con.execute('SELECT COUNT(*) FROM changelog_entry').fetchone()[0]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
