# yaml-language-server: $schema=./table-schema-1.json

name: product_units
datasource: bakery-surreal

id_column: product
columns:
  product: { type: string, flags: [id, title] }
  units: { type: int }

surreal:
  # language=rhai
  rhai: |
    select()
        .from(
            select()
                .expression(ident("lines").alias("line"))
                .from("order")
                .split("lines")
                .subquery())
        .expression(ident("line")["product"].alias("product"))
        .expression(sum(ident("line")["quantity"]).alias("units"))
        .group_by(ident("product"))
        .order_by(ident("units"), "desc")
        .limit(10, 0)
