# yaml-language-server: $schema=./table-schema-1.json

# Table: config_payload_types — lookup table for payload_types.

datasource: ll2
title: payload_types
table: "config/payload_types/"

columns:
  - { name: id, type: int, flags: [id] }
  - { name: name, type: string, flags: [title, searchable] }
